pag_web1/main/urls.py
from django.urls import path    #que entre adjango-urls y de alli importamos los path
from . import views  #importamos las vistas  

app_name = 'main' #variable que ponemos nombre de nuestra app

urlpatterns = [ #aqui se ven todas las secciones de la pagina web
    path('',views.IndexView.as_view(), name="home"),    #path base, se pone vacio (inicio='') xq lo manda a la pag principal
    path('contact/', views.ContactView.as_view(), name="contact"),  #de aqui en + de mas path
    path('blog/', views.BlogView.as_view(), name="blogs"),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),
    path('blog-create/', views.BlogAddInfo.as_view(), name="blog-create"),  #de aqui en + de mas path
    path('review/', views.ReviewView.as_view(), name="reviews"),
    path('review/<slug:slug>', views.ReviewDetailView.as_view(), name="review"),
    path('review-create/', views.ReviewAddInfo.as_view(), name="review-create"),  #de aqui en + de mas path
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),
	path('logout/', views.logoutUser, name="logout"),
]

pag_web1/pag_web1/urls.py
from django.contrib import admin #importa admin
from django.urls import path, include #incluye el path y include
from django.conf import settings #importar la configuracion 
from django.conf.urls.static import static #info static


urlpatterns = [ #url q se estaran administrando (ejem. vaina.com/host/admin = como se accede a admin)
    path("admin/", admin.site.urls),    #se agregan los path que se van a administrar
    path('', include('main.urls',namespace="main"))    #incluye la app como tal (main)
]

if settings.DEBUG:  #llamamos desde settings, vamos a configuracion para colocar los url de arch. staticos y de media
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pag_web1/main/models.py
from django.db import models #importamos model de django
from django.template.defaultfilters import slugify # activamos el slugify
from ckeditor.fields import RichTextField #importamos el texto rico Xd

class Media(models.Model): #modelo encargada de la multimedia

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Contact(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact'
        verbose_name = 'Contact'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'


class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"


class Review(models.Model):

    class Meta:
        verbose_name_plural = 'Review Profiles'
        verbose_name = 'Review'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="review")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Review, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/review/{self.slug}"
#aqui se creara y guardara la base de datos
#cuando se crea la pagina web, primero se ve como va a quedar la base de datos
#la base de datos en django se ve como una clase
#cuando se crea la base de datos toca poner el models.Model (modelo)
#1ro son las librerias, 2do clases y 3ro funciones
#charField = string, si en models no se pone nada = no guarda nada (oara eso es el null)
#las imagenes son de dato tipo FileField
#el doble guin bajo es para decir que es un funcion principal que retorna_valores

pag_web1/main/forms.py
from dataclasses import field, fields
from django import forms
from .models import Contact, Blog, Review

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ContactForm(forms.ModelForm):
    #charfield es string
    name = forms.CharField(max_length=100, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Full name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    # se complementa por @ y .com
    email = forms.EmailField(max_length=254, required=True, 
        widget=forms.TextInput(attrs={
            'placeholder': '*Email..',
            }))
    message = forms.CharField(max_length=1000, required=True,
        widget=forms.Textarea(attrs={
            'placeholder': '*Message..',
            'row': 6, #numero de filas en la ventana de texto (mensaje)
            }))
    #clase meta que indica quien va a recibir la informacion
    class Meta:
        model = Contact
        fields = ('name', 'email', 'message',) #al final de cada parametro se pone , por identificador


class BlogForm(forms.ModelForm):

    author = forms.CharField(max_length=200, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Author name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    name = forms.CharField(max_length=200, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Full name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    description = forms.CharField(max_length=500, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Description..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    body = forms.CharField(max_length=1000, required=True, #el true en lo necesario de ingresar algo
        widget=forms.Textarea(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Info Blog..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    image = forms.ImageField()

    class Meta:
        model = Blog
        fields = ('author','name', 'description', 'body', 'image',) 

class ReviewForm(forms.ModelForm):

    author = forms.CharField(max_length=200, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Author name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    name = forms.CharField(max_length=200, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Full name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    description = forms.CharField(max_length=500, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Description..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    body = forms.CharField(max_length=1000, required=True, #el true en lo necesario de ingresar algo
        widget=forms.Textarea(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Info Blog..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    image = forms.ImageField()

    class Meta:
        model = Review
        fields = ('author','name', 'description', 'body', 'image',) 

class CreateUserForm(UserCreationForm): #form para loggin, despues pasamos a views
    class Meta: #en que tabla se va a guardar
        model = User
        fields = ['username', 'email', 'password1', 'password2']

pag_web1/main/views.py
from django.shortcuts import render #backend renderizar lo que va a pasar de la base de datos(parte vital : proyecta tolo lo que hemos hecho), la parte de url, el index (que recibe y que hace)
from django.contrib import messages #aca va a mostrar los datos solicitados que se piden a travez de django
from django.views import generic #importa el generico = forma en que se muestra lo importado
from .forms import BlogForm, ReviewForm,ContactForm,CreateUserForm #, ReviewForm, BlogForm #el conector de backend y frontend (forms)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect
from .models import ( #importamos todos los datos desde las tablas
	Blog,
	Review,
	)

def registerPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('main:login')
			

		context = {'form':form}
		return render(request, 'main/register.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect("main:home")
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'main/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('main:login')

#hacemos las clases para las vistas
class IndexView(generic.TemplateView):
	template_name = "main/index.html" #asignando la vista

	def get_context_data(self, **kwargs): #funcion q va a obtener la data
		#declaramos las variables donde se va a gaurdar la info
		context = super().get_context_data(**kwargs) #context guardara la informacion de testimonial, certificate, etc.
		blogs = Blog.objects.filter(is_active=True)
		reviews = Review.objects.filter(is_active=True)

		context["blogs"] = blogs
		context["reviews"] = reviews
		return context #regresamos la info

class BlogView(generic.ListView): #aca se suben las noticia (blog), aca se ven 10 lineas
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10 #para q no se sature, mostrara solo 10 lineas... (no toda la info x si es larga)
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True) #retorno de info apenas encuentre todo

class BlogDetailView(generic.DetailView): #aca se encuentra todo (detalles) (despues de clickear la blogview)
	model = Blog
	template_name = "main/blog-detail.html"

class ContactView(generic.FormView):
	template_name = "main/contact.html" #asigno la vista que html recibe
	form_class = ContactForm #creado para recibir info
	success_url = "/" #envia al index apenas de se clic
	
	def form_valid(self, form): 
		form.save()	#guarda info en base de datos
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form) 

class BlogAddInfo(generic.FormView):
	template_name = "main/blog-create.html" #asigno la vista que html recibe
	form_class = BlogForm #creado para recibir info
	success_url = "/" #envia al index apenas de se clic
	
	def form_valid(self, form): 
		form.save()	#guarda info en base de datos
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form) 

class ReviewView(generic.ListView): #aca se suben las noticia (blog), aca se ven 10 lineas
	model = Review
	template_name = "main/review.html"
	paginate_by = 10 #para q no se sature, mostrara solo 10 lineas... (no toda la info x si es larga)
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True) #retorno de info apenas encuentre todo

class ReviewDetailView(generic.DetailView): #aca se encuentra todo (detalles) (despues de clickear la blogview)
	model = Review
	template_name = "main/review-detail.html"

class ReviewAddInfo(generic.FormView):
	template_name = "main/review-create.html" #asigno la vista que html recibe
	form_class = ReviewForm #creado para recibir info
	success_url = "/" #envia al index apenas de se clic
	
	def form_valid(self, form): 
		form.save()	#guarda info en base de datos
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form) 

pag_web1/main/templates/main/blog-create.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-2  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Create Your Blog</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container align-items-center">
        <form id="BlogForm" method="POST" action="{% url 'main:blog-create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
            <label for="author">Author</label>
            {{form.author}}
        
            <label for="name">Name</label>
            {{form.name}}

            <label for="description">Description</label>
            {{form.description}}

            <label for="body">Body</label>
            {{form.body}}

            <label for="image">Image</label>
            {{form.image}}
            <br>
            <br>
            <input class='btn btnPrimary' type="submit" value="Submit">
            <br>
            <br>
        </form>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}

pag_web1/main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Blogs Area</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:blog' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%} 
    

pag_web1/main/templates/main/codigosmoment.html
Antiguo forms (generico)
<section>
    <div class="lightBg">
      <div class="container">
          <form id="ReviewForm" method="POST" action="/review-create/">
          {% csrf_token %}
              <label for="author">Author</label>
              {{form.author}}
              
              <label for="name">Name</label>
              {{form.name}}
  
              <label for="description">Description</label>
              {{form.description}}
  
              <label for="message">Body Blog</label>
              {{form.message}}
  
              <label for="image">Imagen</label>
              {{form.image}}
  
              <input class='btn btnPrimary' type="submit" value="Submit">
          </form>
      </div>
    </div>
  </section>


Fuente bonita de contact con todo al centro
  <div class="text-center mb-5">
    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
    <h1 class="fw-bolder">Send Your Reviews</h1>
    <p class="lead fw-normal text-muted mb-0">asd</p>
</div>

Parte del header muy simple
<section>
    <div class="innerPageBannerCol">
      <div class="container">
        <div class="row g-4 g-md-3  align-items-center">
          <div class="col-md-6">
            <div class="bannerContent">
              <h1 class="xlTitle pb-md-3">Create Your Review</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Phone number input-->
  <div class="form-floating mb-3">
    <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required" />
    <label for="phone">Phone number</label>
    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
</div>

<form id="contactForm" data-sb-form-api-token="API_TOKEN" method="POST" action="/review-create/">
    <!-- Name input-->
    <div class="form-floating mb-3">
        <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
        <label for="name">Full name</label>
        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
        
    </div>
    <!-- Email address input-->
    <div class="form-floating mb-3">
        <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
        <label for="email">Email address</label>
        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
        
    </div>
    <!-- Message input-->
    <div class="form-floating mb-3">
        <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
        <label for="subject">Message</label>
        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
        
    </div>

 <section class="py-5">
      <div class="container px-5">
          <div class="row gx-5 justify-content-center">
              <div class="col-lg-8 col-xl-6">
                  <!-- * * * * * * * * * * * * * * *-->
                  <!-- * * SB Forms Contact Form * *-->
                  <!-- * * * * * * * * * * * * * * *-->
                  <!-- This form is pre-integrated with SB Forms.-->
                  <!-- To make this form functional, sign up at-->
                  <!-- https://startbootstrap.com/solution/contact-forms-->
                  <!-- to get an API token!-->
                  <form id="ReviewForm" method="POST" action="/review-create/">
                    {% csrf_token %}
                      <!-- Name input-->
                      <div class="form-floating mb-3">
                          <input class="form-control" {{form.name}}/>
                          <label for="name">Full name</label>
                          <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                          
                      </div>
                      <!-- Email address input-->
                      <div class="form-floating mb-3">
                          <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                          <label for="email">Email address</label>
                          <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                          <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                          
                      </div>
                      <!-- Message input-->
                      <div class="form-floating mb-3">
                          <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                          <label for="subject">Message</label>
                          <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                          
                      </div>
                      
                      <div class="row gx-5 justify-content-center">
                        <input class='btn btnPrimary' type="submit" value="Submit">
                      </div>
                  </form>
              </div>
          </div>
  </div>
</section>


partes quitada para despues poner:
 <!-- reviews section-->
 <section>
  <div class="sectionSpace">
    <div class="container">
      <div class="reviewCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Reviews</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'main:reviews' %}" class="simpleLink">View all</a>
          </div>
        </div>
        
        <div class="reviewCard">
          <div class="row g-4 align-items-center">
          {% for p in reviews %}
          {% if p.is_active %}
            <div class="col-md-auto">
              <div class="reviewImgCol">
                <a href="{% url 'main:review' slug=p.slug %}"><img src="{{p.image.url}}" alt="..." wight = 120px height = auto></a>
              </div>
            </div>
            <div class="col-md">
              <div class="reviewContentCol">
                <h4 class="lgTitle"><a href="{% url 'main:review' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="reviewOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p>{{p.description}}</p>
              </div>
            </div>
          {% endif %}
          {% endfor %}
          </div>
        </div>
        
      </div>
    </div>
  </div>
</section>
<!-- Blog section-->
<section>
  <div class="innerPageBannerColI">
    <div class="sectionSpace">
      <div class="container">
        <div class="reviewCol">
          <div class="row pb-3">
            <div class="col">
              <h4 class="smText regular">Blogs</h4>
            </div>
            <div class="col-auto">
              <a href="{% url 'main:blogs' %}" class="simpleLink">View all</a>
            </div>
          </div>
        
          <div class="portfolioCard">
            <div class="row g-5 align-items-center">
            {% for p in blogs %}
            {% if p.is_active %}
              <div class="col-md-auto">
                <div class="portfolioImgCol">
                  <a href="{% url 'main:blog' slug=p.slug %}"><img src="{{p.image.url}}" alt="..." wight = 120px height = auto></a>
                </div>
              </div>
              <div class="col-md">
                <div class="portfolioContentCol">
                  <h4 class="lgTitle"><a href="{% url 'main:blog' slug=p.slug %}">{{p.name}}</a></h4>
                  <ul class="portfolioOption">
                    <li><span class="dateLbl">{{p.date.year}}</span></li>
                  </ul>
                  <p>{{p.description}}</p>
                </div>
              </div>
            {% endif %}
            {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>



<form id="BlogForm" method="POST" action="{% url 'main:blogaddinfo' %}", enctype="multipart/form-data">
  {% csrf_token %}
      <label for="author">Author</label>
      {{form.author}}

      <label for="name">Name</label>
      {{form.name}}

      <label for="description">Description</label>
      {{form.description}}

      <label for="body">Body</label>
      {{form.body}}

      <label for="image">Image</label>
      {{form.image}}
      <br>
      <br>

      <input class='btn btnPrimary' type="submit" value="Submit">
  </form>


  <form id="contactForm" method="POST" action="/contact/">
    {% csrf_token %}
    <br>
        <label for="name">Name</label>
        {{form.name}}

        <label for="email">Email</label>
        {{form.email}}

        <label for="subject">Message</label>
        {{form.message}}

        <input class='btn btnPrimary' type="submit" value="Submit">
        <br>
        <br>
    </form>


    {% block content %}
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <div class="row g-4 g-md-2  align-items-center">
            <div class="col-md-6">
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3">Contact us below</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <section>
      <div class="lightBg">
        <div class="container">
          <form id="BlogForm" method="POST" action="{% url 'main:blogaddinfo' %}", enctype="multipart/form-data">
            {% csrf_token %}
            <label for="author">Author</label>
            {{form.author}}
      
            <label for="name">Name</label>
            {{form.name}}
      
            <label for="description">Description</label>
            {{form.description}}
      
            <label for="body">Body</label>
            {{form.body}}
      
            <label for="image">Image</label>
            {{form.image}}
            <br>
            <br>
      
            <input class='btn btnPrimary' type="submit" value="Submit">
                <br>
                <br>
            </form>
        </div>
      </div>
    </section>