pag_web1/main/urls.py
from django.urls import path    #que entre adjango-urls y de alli importamos los path
from . import views  #importamos las vistas  

app_name = 'main' #variable que ponemos nombre de nuestra app

urlpatterns = [ #aqui se ven todas las secciones de la pagina web
    path('',views.IndexView.as_view(), name="home"),    #path base, se pone vacio (inicio='') xq lo manda a la pag principal
    path('contact/', views.ContactView.as_view(), name="contact"),  #de aqui en + de mas path
    path('blog/', views.BlogView.as_view(), name="blogs"),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),
    path('blog-create/', views.BlogAddInfo.as_view(), name="blog-create"),  #de aqui en + de mas path
    path('review/', views.ReviewView.as_view(), name="reviews"),
    path('review/<slug:slug>', views.ReviewDetailView.as_view(), name="review"),
    path('review-create/', views.ReviewAddInfo.as_view(), name="review-create"),  #de aqui en + de mas path
    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),
	path('logout/', views.logoutUser, name="logout"),
]

pag_web1/pag_web1/urls.py
from django.contrib import admin #importa admin
from django.urls import path, include #incluye el path y include
from django.conf import settings #importar la configuracion 
from django.conf.urls.static import static #info static


urlpatterns = [ #url q se estaran administrando (ejem. vaina.com/host/admin = como se accede a admin)
    path("admin/", admin.site.urls),    #se agregan los path que se van a administrar
    path('', include('main.urls',namespace="main"))    #incluye la app como tal (main)
]

if settings.DEBUG:  #llamamos desde settings, vamos a configuracion para colocar los url de arch. staticos y de media
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pag_web1/main/models.py
from django.db import models #importamos model de django
from django.template.defaultfilters import slugify # activamos el slugify
from ckeditor.fields import RichTextField #importamos el texto rico Xd

class Media(models.Model): #modelo encargada de la multimedia

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Contact(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact'
        verbose_name = 'Contact'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'


class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"


class Review(models.Model):

    class Meta:
        verbose_name_plural = 'Review Profiles'
        verbose_name = 'Review'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="review")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Review, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/review/{self.slug}"
#aqui se creara y guardara la base de datos
#cuando se crea la pagina web, primero se ve como va a quedar la base de datos
#la base de datos en django se ve como una clase
#cuando se crea la base de datos toca poner el models.Model (modelo)
#1ro son las librerias, 2do clases y 3ro funciones
#charField = string, si en models no se pone nada = no guarda nada (oara eso es el null)
#las imagenes son de dato tipo FileField
#el doble guin bajo es para decir que es un funcion principal que retorna_valores

pag_web1/main/forms.py
from dataclasses import field, fields
from django import forms
from .models import Contact, Blog, Review

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ContactForm(forms.ModelForm):
    #charfield es string
    name = forms.CharField(max_length=100, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Full name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    # se complementa por @ y .com
    email = forms.EmailField(max_length=254, required=True, 
        widget=forms.TextInput(attrs={
            'placeholder': '*Email..',
            }))
    message = forms.CharField(max_length=1000, required=True,
        widget=forms.Textarea(attrs={
            'placeholder': '*Message..',
            'row': 6, #numero de filas en la ventana de texto (mensaje)
            }))
    #clase meta que indica quien va a recibir la informacion
    class Meta:
        model = Contact
        fields = ('name', 'email', 'message',) #al final de cada parametro se pone , por identificador


class BlogForm(forms.ModelForm):

    author = forms.CharField(max_length=200, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Author name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    name = forms.CharField(max_length=200, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Full name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    description = forms.CharField(max_length=500, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Description..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    body = forms.CharField(max_length=1000, required=True, #el true en lo necesario de ingresar algo
        widget=forms.Textarea(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Info Blog..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    image = forms.ImageField()

    class Meta:
        model = Blog
        fields = ('author','name', 'description', 'body', 'image',) 

class ReviewForm(forms.ModelForm):

    author = forms.CharField(max_length=200, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Author name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    name = forms.CharField(max_length=200, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Full name..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    description = forms.CharField(max_length=500, required=True, #el true en lo necesario de ingresar algo
        widget=forms.TextInput(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Description..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    body = forms.CharField(max_length=1000, required=True, #el true en lo necesario de ingresar algo
        widget=forms.Textarea(attrs={ #lo que vas a escribir es un textinput
            'placeholder': '*Info Blog..', #placerholder = indicacion del full name que se borra cuando lo seleccionas, a la derecha se pone lo que se quiere ver
             }))
    image = forms.ImageField()

    class Meta:
        model = Review
        fields = ('author','name', 'description', 'body', 'image',) 

class CreateUserForm(UserCreationForm): #form para loggin, despues pasamos a views
    class Meta: #en que tabla se va a guardar
        model = User
        fields = ['username', 'email', 'password1', 'password2']

pag_web1/main/views.py
from django.shortcuts import render #backend renderizar lo que va a pasar de la base de datos(parte vital : proyecta tolo lo que hemos hecho), la parte de url, el index (que recibe y que hace)
from django.contrib import messages #aca va a mostrar los datos solicitados que se piden a travez de django
from django.views import generic #importa el generico = forma en que se muestra lo importado
from .forms import BlogForm, ReviewForm,ContactForm,CreateUserForm #, ReviewForm, BlogForm #el conector de backend y frontend (forms)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect
from .models import ( #importamos todos los datos desde las tablas
	Blog,
	Review,
	)

def registerPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('main:login')
			

		context = {'form':form}
		return render(request, 'main/register.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect("main:home")
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'main/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('main:login')

#hacemos las clases para las vistas
class IndexView(generic.TemplateView):
	template_name = "main/index.html" #asignando la vista

	def get_context_data(self, **kwargs): #funcion q va a obtener la data
		#declaramos las variables donde se va a gaurdar la info
		context = super().get_context_data(**kwargs) #context guardara la informacion de testimonial, certificate, etc.
		blogs = Blog.objects.filter(is_active=True)
		reviews = Review.objects.filter(is_active=True)

		context["blogs"] = blogs
		context["reviews"] = reviews
		return context #regresamos la info

class BlogView(generic.ListView): #aca se suben las noticia (blog), aca se ven 10 lineas
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10 #para q no se sature, mostrara solo 10 lineas... (no toda la info x si es larga)
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True) #retorno de info apenas encuentre todo

class BlogDetailView(generic.DetailView): #aca se encuentra todo (detalles) (despues de clickear la blogview)
	model = Blog
	template_name = "main/blog-detail.html"

class ContactView(generic.FormView):
	template_name = "main/contact.html" #asigno la vista que html recibe
	form_class = ContactForm #creado para recibir info
	success_url = "/" #envia al index apenas de se clic
	
	def form_valid(self, form): 
		form.save()	#guarda info en base de datos
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form) 

class BlogAddInfo(generic.FormView):
	template_name = "main/blog-create.html" #asigno la vista que html recibe
	form_class = BlogForm #creado para recibir info
	success_url = "/" #envia al index apenas de se clic
	
	def form_valid(self, form): 
		form.save()	#guarda info en base de datos
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form) 

class ReviewView(generic.ListView): #aca se suben las noticia (blog), aca se ven 10 lineas
	model = Review
	template_name = "main/review.html"
	paginate_by = 10 #para q no se sature, mostrara solo 10 lineas... (no toda la info x si es larga)
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True) #retorno de info apenas encuentre todo

class ReviewDetailView(generic.DetailView): #aca se encuentra todo (detalles) (despues de clickear la blogview)
	model = Review
	template_name = "main/review-detail.html"

class ReviewAddInfo(generic.FormView):
	template_name = "main/review-create.html" #asigno la vista que html recibe
	form_class = ReviewForm #creado para recibir info
	success_url = "/" #envia al index apenas de se clic
	
	def form_valid(self, form): 
		form.save()	#guarda info en base de datos
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form) 

pag_web1/main/templates/main/partials/footer.html
{% load static %}
<!-- ================================
Start Footer
================================= -->
<footer class="bg-dark py-4 mt-auto">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Your Website 2022</div></div>
            <div class="col-auto">
                <a class="link-light small" href="#!">Privacy</a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="#!">Terms</a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="{% url 'main:contact' %}">Contact</a>
            </div>
        </div>
    </div>
</footer>

<!-- ================================
End Footer
================================= -->

pag_web1/main/templates/main/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

pag_web1/main/templates/main/partials/nav.html
{% load static %}
<!-- ================================
Start Navigation Bar
================================= -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'main:home' %}"><img src="static/assets/logo1.png" alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'main:home' %}">Home</a></li>
                

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Blogs</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                        <li><a class="dropdown-item" href="{% url 'main:blogs' %}">Blogs</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:blog-create' %}">Create Blog</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownReview" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reviews</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownReview">
                        <li><a class="dropdown-item" href="{% url 'main:reviews' %}">Reviews</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:review-create' %}">Create Review</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownReview" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Log in/out</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownReview">
                        <li><a class="dropdown-item" href="{%url 'main:login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{%url 'main:logout' %}">Logout</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'main:contact' %}">Contact Us</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- ================================
End Navigation Bar
================================= -->